"""公共层：server 与 client 共用，且不属于纯游戏规则的代码。"""

from common.console import (
    verbose,
    success,
    warn,
    error,
    fatal,
    user_confirm,
    check_packages,
    register_signal_handler,
    disable_echo,
    enable_echo,
)
from common.card_io import (
    str_to_int,
    int_to_str,
    strs_to_ints,
    cards_to_ints,
    cards_to_strs,
    draw_cards,
    calculate_score,
    get_card_count,
    head_master_in_team,
    calculate_head_master_team_score,
    calculate_normal_team_score,
    calculate_team_scores,
    last_played,
)

__all__ = [
    "verbose",
    "success",
    "warn",
    "error",
    "fatal",
    "user_confirm",
    "check_packages",
    "register_signal_handler",
    "disable_echo",
    "enable_echo",
    "str_to_int",
    "int_to_str",
    "strs_to_ints",
    "cards_to_ints",
    "cards_to_strs",
    "draw_cards",
    "calculate_score",
    "get_card_count",
    "head_master_in_team",
    "calculate_head_master_team_score",
    "calculate_normal_team_score",
    "calculate_team_scores",
    "last_played",
]
